### ISSUE TITLE
Warning message: The following regions were missing and are being set to NA: NA

### ISSUE THREAD

**Issue by TimKeighley** [arilamstein/choroplethr#4] opened 2015-12-21 23:16 UTC
Using the "Creating Administrative Level 1 Maps" vignette,

```r
library(choroplethr)
library(choroplethrAdmin1)

data(df_japan_census)
df_japan_census$value = df_japan_census$pop_2010

admin1_choropleth(country.name = "japan", 
    df           = df_japan_census, 
    title        = "2010 Japan Population Estimates", 
    legend       = "Population", 
    num_colors   = 1)
```

This produces a warning

```
Warning message:
In self$bind() :
  The following regions were missing and are being set to NA: NA
```

This happens because you do a `left_join` on `region`, however some regions are `NA`.

```
> any(is.na(get_admin1_map("japan")$region))
[1] TRUE
```

I suggest that you filter out any regions that are `NA` in `map.df`, possibly in the `initialize` function.

**Comment by arilamstein** [comment] 2015-12-22 18:03
I'm curious about what those NA regions are and why they are in the map at all. Can you provide an image of them mapped, perhaps with ggplot2? My guess is that they are very small islands. I thought that all of Japan was divided into prefectures, but perhaps these islands are not part of any prefecture, but instead owned by the federal government.

For reference, here is how to find more information about the Administrative Level 1 map that choroplethr uses:

    library(choroplethrAdmin1) 
    ?admin1.map


As you can see, the map is version 3.0.0 of the [Natural Earth Admin1 Map](http://www.naturalearthdata.com/downloads/10m-cultural-vectors/10m-admin-1-states-provinces/). It might be worth it to bring this issue up with them directly. I am reluctant to make changes to the map on my end.

The warning itself seems wierd because the regions we are missing are NA regions. But in general the warning is useful because there is often more than one way to name a region, and for the data to appear on the map the naming needs to be identical. 

It looks like that map is actually on github ([link](https://github.com/nvkelso/natural-earth-vector/blob/master/CHANGELOG)) and is owned by @nvkelso. I'm cc'ing him in case he has any insights on this.

**Comment by TimKeighley** [comment] 2015-12-22 23:19
I think for the most part they are small islands that are not associated with an admin1 region. In Japan:

```r
japan <- choroplethrAdmin1::get_admin1_map("japan")
japanNA <- subset(japan, is.na(region))
```
```
> table(japan$note, useNA = "ifany")

JPN-99 (Japan minor island)                        <NA> 
                        128                       14417 
> table(japanNA$note)

JPN-99 (Japan minor island) 
                        128 
> table(japan$featurecla, useNA = "ifany")

Admin-1 minor island   Admin-1 scale rank 
                 128                14417 
> table(japanNA$featurecla)

Admin-1 minor island 
                 128 
```

However in Australia

```r
australia <- choroplethrAdmin1::get_admin1_map("australia")
australiaNA <- subset(australia, is.na(region))
```
```
> table(australia$note, useNA = "ifany")

 <NA> 
17141 
> table(australia$name, useNA = "ifany")

australian capital territory         jervis bay territory             macquarie island 
                         157                           24                           34 
             new south wales               norfolk island           northern territory 
                        1513                           16                         3213 
                  queensland              south australia                     tasmania 
                        3540                         1498                         1537 
                    victoria            western australia 
                        1072                         4537 
> table(australiaNA$name, useNA = "ifany")

macquarie island   norfolk island 
              34               16 
> table(australia$featurecla, useNA = "ifany")

Admin-1 aggregation  Admin-1 scale rank 
                 34               17107 
> table(australiaNA$featurecla)

Admin-1 aggregation  Admin-1 scale rank 
                 34                  16 
```

I'm not suggesting that you get rid of the warning or that you change the map. I agree that the warning has a useful function when matching regions and should be kept. However, since you use the region field to match between what the user supplies and the map, I think that it is reasonable to filter out regions that are `NA` and thus can never be matched in this way.

Actually, the reason that I started investigating this in the first place is because I find the warning useful and don't want to suppress it, however I think that the users of the product I am developing will be confused by the `NA` warning message. I would like to keep the warning message for "proper" mismatches and not show the `NA` warning.

I previously suggested that you could do this filtering in the `initialize` function, but perhaps a more appropriate place is the `bind` function, just before it does the `left_join`.

Investigating further

```r
data(admin1.map, package = "choroplethrAdmin1")
admin1.mapNA <- subset(admin1.map, is.na(region))

table(admin1.mapNA$admin, useNA = "ifany")
table(admin1.mapNA$name, useNA = "ifany")
table(admin1.mapNA$note, useNA = "ifany")
table(admin1.mapNA$featurecla, useNA = "ifany")
```

it looks like several countries have `NA` regions. Looking at the `note` field, a lot of them are marked as "minor island".

**Comment by arilamstein** [comment] 2015-12-22 23:36
Since the purpose of the map (at least within the choroplethr ecosystem) is
to generate choropleth maps of admin1 regions, my inclination is to simply
remove all NA regions from the map. I can see two potential benefits of
this:

1. Reduce the size of the map
2. Reduce clutter on the map. In the [Japan](
https://cran.r-project.org/web/packages/choroplethr/vignettes/i-creating-admin1-maps.html)
example, those small outlier islands I think are more visually distracting
than helpful.

 This woudn't be the first time that I have modified maps that I ship. For
example, in the US maps I remove Puerto Rico and the Aleutian Islands that
cross the antemeridian. I just make sure that I document it in the help.

I don't have time to code this up now, but feel free to make a pull request
with the changed map, do some tests (e.g. verify that we have the same
number of regions before and after) and submit some screenshots (e.g. of
Japan, Australia) just to make sure that we're not losing any functionality.

**Comment by arilamstein** [comment] 2015-12-30 03:34
@TimKeighley I have just updated the admin1 map. In addition to removing the warning, I am seeing a substantial decrease in the time it takes to generate the Japan admin1 map (from 20s to 3s). Can you please do some tests on your end? If it looks good to you I will submit this to CRAN. Note that to do this you will need to install the dev version of [https://github.com/arilamstein/choroplethradmin1](choroplethrAdmin1). If you need help with that let me know.

**Comment by TimKeighley** [comment] 2015-12-30 03:43
@arilamstein Looks good to me. And indeed much quicker. Thanks.

**Comment by arilamstein** [comment] 2015-12-30 03:46
Neat. I will look into getting this on CRAN soon. Although it might take a
little while due to the holidays. Also, the next version of choroplethr
will support reference maps for admin1 maps. That is, you will be able to
overlay your choropleth map over a google map. Stay tuned.

**Comment by nvkelso** [comment] 2015-12-30 06:12
Confirmed that NA "regions" are remainder that should be associated with a particular admin-1 region, but haven't. It's okay to drop them for choropleth map, and they are only good at web map zooms 7-8. It is odd, though, your build time is so much faster. Uninformed speculation: Could be how you pack attrs onto exploded polygons?

**Comment by arilamstein** [comment] 2015-12-30 15:43
Thanks @nvkelso . In addition to removing the NA regions I also dropped many of the columns that were not necessary for creating the choropleth map. I forget the exact numbers, but I think that this reduced the number of columns from ~70 to ~5. As a result of these changes the map size in R went from 545.9Mb to 82.2 Mb. It's likely that the speed increase was more due to dropping the columns than removing the NA regions - at this point I don't remember.

By the way, thanks so much for your work on Natural Earth Data, and the permissive license terms. In addition to the admin1 map, the main [choroplethr](https://github.com/arilamstein/choroplethr) project uses your country map. I don't have exact stats, but my impression is that these maps are now used on a daily basis by R users.

**Comment by arilamstein** [comment] 2015-12-31 19:56
The new version of the choroplethrAdmin1 package, which removes the NA regions, was accepted by CRAN yesterday so I am closing this ticket.

**Closed by arilamstein** 2015-12-31 19:56 UTC
